

version: 2

sources:
  - name: RESTAUPARIS
    tables:
      - name : INSEE_etablissement
      - name : testbapt5
      - name : RestauParis_new_cat5
      - name: cat_restau_abdellah
      - name : QuartiersParis